import "fake-indexeddb/auto";
import { deleteDB } from "idb";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AgentView } from "./AgentView";
import { createDemoData } from "./demoData";
import { loadAgentConfig, listConversations, saveConversation, saveAgentConfig } from "../agent/storage";
import { DEFAULT_AGENT_CONFIG } from "../agent/types";
import * as runner from "../agent/runner";

beforeEach(async () => { await deleteDB("pixivpulse-agent"); sessionStorage.clear(); localStorage.clear(); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
describe("Agent workspace", () => {
  it("streams public paragraphs apart from collapsed operations and copies only the final answer", async () => {
    await saveAgentConfig({ ...DEFAULT_AGENT_CONFIG, apiKey: "test-key" });
    let hooks!: runner.RunHooks, finish!: () => void;
    vi.spyOn(runner, "runAgent").mockImplementation(async (_c, _m, _d, _p, _s, value) => { hooks = value; await new Promise<void>(resolve => { finish = resolve; }); });
    const clipboard = vi.fn().mockResolvedValue(undefined);
    Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: clipboard } });
    render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.change(await screen.findByRole("textbox", { name: "向 Agent 提问" }), { target: { value: "检查数据缺口" } });
    fireEvent.click(screen.getByRole("button", { name: "发送" })); await waitFor(() => expect(hooks).toBeDefined());
    hooks.onCommentary?.("p", "先核对"); await screen.findByText("先核对");
    hooks.onCommentary?.("p", "先核对记录日期，再判断缺口。");
    hooks.onOperation?.({ id: "o", kind: "operation", text: "检查数据完整性", at: "now", status: "running" });
    expect(await screen.findByText("先核对记录日期，再判断缺口。")).toBeVisible();
    const operation = (await screen.findByText("检查数据完整性")).closest("details")!;
    expect(operation).not.toHaveAttribute("open");
    expect(document.querySelector(".agent-answer .agent-markdown")?.textContent).toBe("检查数据缺口");
    hooks.onOperation?.({ id: "o", kind: "operation", text: "检查数据完整性", at: "now", status: "complete" });
    hooks.onText("已确认的最终结论。"); finish();
    await screen.findByRole("button", { name: "重新生成" });
    fireEvent.click(within(screen.getByText("已确认的最终结论。").closest("article")!).getByRole("button", { name: "复制" }));
    await waitFor(() => expect(clipboard).toHaveBeenCalledWith("已确认的最终结论。"));
    const saved = (await listConversations("preview"))[0]!.messages.at(-1)!;
    expect(saved.activity?.map(item => item.kind)).toEqual(["commentary", "operation"]);
    expect(saved.activity?.[0]?.text).toBe("先核对记录日期，再判断缺口。");
    expect(saved.content).toBe("已确认的最终结论。");
  });
  it("opens a fresh draft on entry, re-entry and remount while retaining selectable history", async () => {
    const data = createDemoData();
    await saveConversation({ id: "old", title: "旧对话", accountId: "preview", updatedAt: "now", messages: [{ id: "u", role: "user", content: "旧问题", status: "complete", at: "now", traces: [] }] });
    localStorage.setItem("pixivpulse-agent-selection:preview", "old");
    const view = render(<AgentView data={data} isPreview active />);
    await screen.findByRole("textbox", { name: "向 Agent 提问" });
    expect(screen.queryByText("旧问题")).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "旧对话" }));
    await screen.findByText("旧问题");
    view.rerender(<AgentView data={data} isPreview active={false} />);
    view.rerender(<AgentView data={data} isPreview active />);
    expect(screen.queryByText("旧问题")).not.toBeInTheDocument();
    expect(screen.getByRole("textbox", { name: "向 Agent 提问" })).toHaveValue("");
    fireEvent.click(screen.getByRole("button", { name: "旧对话" }));
    await screen.findByText("旧问题");
    view.unmount(); render(<AgentView data={data} isPreview active />);
    await screen.findByRole("textbox", { name: "向 Agent 提问" });
    expect(screen.queryByText("旧问题")).not.toBeInTheDocument();
    expect(await listConversations("preview")).toHaveLength(1);
  });
  it("copies Markdown, edits drafts and forks historical retries without losing later turns", async () => {
    await saveAgentConfig({ ...DEFAULT_AGENT_CONFIG, apiKey: "test-key" });
    const messages = ["第一问", "**第一答**", "第二问", "第二答"].map((content, index) => ({ id: `m${index}`, role: index % 2 ? "assistant" as const : "user" as const, content, at: "now", status: "complete" as const, traces: [] }));
    await saveConversation({ id: "original", accountId: "preview", title: "原对话", updatedAt: "now", messages });
    const clipboard = vi.fn().mockResolvedValue(undefined);
    Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: clipboard } });
    const run = vi.spyOn(runner, "runAgent").mockImplementation(async (_c, history, _d, _p, _s, hooks) => {
      expect(history.map(row => row.content)).toEqual(["第一问"]);
      hooks.onText("新的第一答");
    });
    render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.click(await screen.findByRole("button", { name: "原对话" }));
    const answer = (await screen.findByText("第一答")).closest("article")!;
    fireEvent.click(within(answer).getByRole("button", { name: "复制" }));
    await waitFor(() => expect(clipboard).toHaveBeenCalledWith("**第一答**"));
    fireEvent.click(within(answer).getByRole("button", { name: "引用追问" }));
    expect((screen.getByRole("textbox", { name: "向 Agent 提问" }) as HTMLTextAreaElement).value).toContain("> **第一答**");
    expect(run).not.toHaveBeenCalled();
    fireEvent.click(screen.getAllByRole("button", { name: "重新编辑" })[1]!);
    expect(screen.getByRole("textbox", { name: "向 Agent 提问" })).toHaveValue("第二问");
    fireEvent.click(within(answer).getByRole("button", { name: "从此处重试" }));
    await screen.findByText("新的第一答");
    await waitFor(async () => {
      const rows = await listConversations("preview");
      expect(rows).toHaveLength(2);
      expect(rows.find(row => row.id === "original")!.messages).toEqual(messages);
      expect(rows.find(row => row.id !== "original")!.messages.map(row => row.content)).toEqual(["第一问", "新的第一答"]);
    });
  });
  it("removes legacy budgets from settings and saved config while preserving credentials and reading preferences", async () => {
    const legacy = { ...DEFAULT_AGENT_CONFIG, apiKey: "retained-key", model: "retained-model", inputBudget: 64000, totalInputBudget: 160000, maxOutputTokens: 512, readingDepth: "deep" as const };
    await saveAgentConfig(legacy);
    render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.click(await screen.findByRole("button", { name: "连接配置" }));
    expect(screen.queryByLabelText(/输入预算|最大输出|上下文窗口/)).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "保存配置" }));
    await screen.findByText("连接配置已保存。");
    const saved = await loadAgentConfig();
    expect(saved).toMatchObject({ apiKey: "retained-key", model: "retained-model", readingDepth: "deep" });
    expect(saved).not.toHaveProperty("inputBudget"); expect(saved).not.toHaveProperty("maxOutputTokens");
  });
  it("shows live progress and flushes the last text burst while generation remains open", async () => {
    await saveAgentConfig({ ...DEFAULT_AGENT_CONFIG, apiKey: "test-key" });
    vi.spyOn(runner, "runAgent").mockImplementation(async (_c, _m, _d, _p, signal, hooks) => {
      hooks.onProgress?.("正在定位作品"); hooks.onText("前半"); hooks.onText("后半");
      return new Promise((_resolve, reject) => signal.addEventListener("abort", () => reject(new Error("aborted")), { once: true }));
    });
    render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.click(await screen.findByRole("button", { name: "向上展开输入框" }));
    expect(screen.getByRole("button", { name: "收起输入框" })).toHaveAttribute("aria-expanded", "true");
    fireEvent.change(screen.getByRole("textbox", { name: "向 Agent 提问" }), { target: { value: "进度测试" } });
    fireEvent.click(screen.getByRole("button", { name: "发送" }));
    await screen.findByText("前半后半");
    expect(screen.getByText(/正在定位作品 · 已用时/)).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "停止生成" }));
    await screen.findByText("生成已停止，可重试。");
  });
  it("separates tool commentary, auto-folds for the answer and restores expandable history", async () => {
    await saveAgentConfig({ ...DEFAULT_AGENT_CONFIG, apiKey: "test-key" });
    let hooks!: runner.RunHooks, finish!: () => void;
    vi.spyOn(runner, "runAgent").mockImplementation(async (_c, _m, _d, _p, _s, value) => { hooks = value; hooks.onProgress?.("读取正文：《示例章节》"); await new Promise<void>(resolve => { finish = resolve; }); });
    const view = render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.change(await screen.findByRole("textbox", { name: "向 Agent 提问" }), { target: { value: "比较正文" } });
    fireEvent.click(screen.getByRole("button", { name: "发送" }));
    await screen.findByRole("button", { name: "收起执行过程" });
    await waitFor(() => expect(hooks).toBeDefined());
    hooks.onText("先核对样本范围。"); hooks.onToolTurn?.("先核对样本范围。");
    await waitFor(() => expect(document.querySelector(".assistant .agent-answer .agent-markdown")?.textContent).toBe(""));
    expect(await screen.findByText("先核对样本范围。")).toBeVisible();
    hooks.onProgress?.("结合已获取的证据组织回答"); hooks.onText("保留角色行动的细节。");
    fireEvent.click(await screen.findByRole("button", { name: "收起执行过程" }));
    expect(screen.getByText("先核对样本范围。")).not.toBeVisible();
    fireEvent.click(screen.getByRole("button", { name: "展开执行过程" }));
    expect(screen.getByText("先核对样本范围。")).toBeVisible();
    finish(); await screen.findByRole("button", { name: "重新生成" });
    await screen.findByRole("button", { name: "展开执行过程" });
    const saved = (await listConversations("preview"))[0]!.messages.at(-1)!;
    expect(saved.content).toBe("保留角色行动的细节。");
    expect(saved.progress).toContainEqual(expect.objectContaining({ detail: "先核对样本范围。" }));
    view.unmount(); render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.click(await screen.findByRole("button", { name: "比较正文" }));
    fireEvent.click(await screen.findByRole("button", { name: "展开执行过程" }));
    expect(screen.getByText("先核对样本范围。")).toBeVisible();
  });
  it("leaves settings when creating a conversation", async () => {
    render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.click(await screen.findByRole("button", { name: "连接配置" }));
    fireEvent.click(screen.getByRole("button", { name: "新对话" }));
    expect(screen.getByRole("textbox", { name: "向 Agent 提问" })).toBeInTheDocument();
  });
  it("allows independent concurrent conversations and stops only the selected run", async () => {
    await saveAgentConfig({ ...DEFAULT_AGENT_CONFIG, apiKey: "test-key" });
    const signals: AbortSignal[] = [];
    vi.spyOn(runner, "runAgent").mockImplementation(async (_c, _m, _d, _p, signal) => {
      signals.push(signal);
      return new Promise((_resolve, reject) => signal.addEventListener("abort", () => reject(new Error("aborted")), { once: true }));
    });
    render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.change(await screen.findByRole("textbox", { name: "向 Agent 提问" }), { target: { value: "会话甲" } });
    fireEvent.click(screen.getByRole("button", { name: "发送" }));
    await waitFor(() => expect(signals).toHaveLength(1));
    fireEvent.click(screen.getByRole("button", { name: "新对话" }));
    fireEvent.change(screen.getByRole("textbox", { name: "向 Agent 提问" }), { target: { value: "会话乙" } });
    fireEvent.click(screen.getByRole("button", { name: "发送" }));
    await waitFor(() => expect(signals).toHaveLength(2));
    fireEvent.click(screen.getByRole("button", { name: /^会话甲/ }));
    fireEvent.click(screen.getByRole("button", { name: "停止生成" }));
    await screen.findByText("生成已停止，可重试。");
    expect(signals[0]!.aborted).toBe(true);
    expect(signals[1]!.aborted).toBe(false);
    fireEvent.click(screen.getByRole("button", { name: /^会话乙/ }));
    fireEvent.click(screen.getByRole("button", { name: "停止生成" }));
    await waitFor(async () => expect((await listConversations("preview")).every(row => row.messages.at(-1)?.status === "stopped")).toBe(true));
  });
  it("keeps a hidden run alive when re-entry opens a fresh draft", async () => {
    await saveAgentConfig({ ...DEFAULT_AGENT_CONFIG, apiKey: "test-key" });
    let finish!: () => void, signal!: AbortSignal;
    vi.spyOn(runner, "runAgent").mockImplementation(async (_c, _m, _d, _p, value, hooks) => {
      signal = value;
      await new Promise<void>(resolve => { finish = resolve; });
      hooks.onText("后台完成的回答");
    });
    const data = createDemoData(), view = render(<AgentView data={data} isPreview active />);
    fireEvent.change(await screen.findByRole("textbox", { name: "向 Agent 提问" }), { target: { value: "后台任务" } });
    fireEvent.click(screen.getByRole("button", { name: "发送" }));
    await waitFor(() => expect(finish).toBeDefined());
    view.rerender(<AgentView data={data} isPreview active={false} />);
    view.rerender(<AgentView data={data} isPreview active />);
    expect(signal.aborted).toBe(false);
    expect(screen.getByRole("textbox", { name: "向 Agent 提问" })).toHaveValue("");
    expect(screen.queryByRole("button", { name: "停止生成" })).not.toBeInTheDocument();
    finish();
    await waitFor(async () => expect((await listConversations("preview"))[0]?.messages.at(-1)?.status).toBe("complete"));
    expect(screen.queryByText("后台完成的回答")).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "后台任务" }));
    expect(await screen.findByText("后台完成的回答")).toBeVisible();
  });
  it("starts with DeepSeek Responses and requires explicit data sharing", async () => {
    render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.click(await screen.findByRole("button", { name: "连接配置" }));
    expect(screen.getByLabelText("API 协议")).toHaveValue("responses");
    expect(screen.getByLabelText("Model name")).toHaveValue("deepseek-v4-flash");
    expect(screen.getByRole("checkbox", { name: /^允许 Agent/ })).not.toBeChecked();
    fireEvent.change(screen.getByLabelText("API key"), { target: { value: "test-ui-key" } });
    fireEvent.click(screen.getByRole("checkbox", { name: /^允许 Agent/ }));
    fireEvent.click(screen.getByRole("button", { name: "保存配置" }));
    await screen.findByText("连接配置已保存。");
    expect((await loadAgentConfig()).shareData).toBe(true);
    expect((await loadAgentConfig()).apiKey).toBe("test-ui-key");
  });
  it("saves the real user question, accumulated answer and traces; restores and deletes conversation", async () => {
    await saveAgentConfig({ ...DEFAULT_AGENT_CONFIG, apiKey: "test-ui-key", shareData: true });
    vi.spyOn(runner, "runAgent").mockImplementation(async (_config, messages, _data, _preview, _signal, hooks) => {
      expect(messages.at(-1)?.content).toBe("请分析收藏");
      hooks.onText("基于真实记录 [S1]");
      await hooks.onTrace({ id: "S1", name: "get_overview", arguments: "{}", result: '{"views":42}', at: "now" });
    });
    const view = render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.change(await screen.findByRole("textbox", { name: "向 Agent 提问" }), { target: { value: "请分析收藏" } });
    fireEvent.click(screen.getByRole("button", { name: "发送" }));
    await screen.findByRole("button", { name: "重新生成" });
    const saved = await listConversations("preview");
    expect(saved[0]?.messages[1]).toMatchObject({ status: "complete", content: "基于真实记录 [S1]", traces: [{ id: "S1" }] });
    view.unmount(); render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.click(await screen.findByRole("button", { name: "请分析收藏" }));
    await screen.findByText("基于真实记录 [S1]");
    fireEvent.click(screen.getByRole("button", { name: "删除对话 请分析收藏" }));
    fireEvent.click(screen.getByRole("button", { name: "确认删除" }));
    await waitFor(() => expect(screen.queryByRole("dialog")).not.toBeInTheDocument());
    expect(await listConversations("preview")).toEqual([]);
  });
  it("aborts an active run and marks the saved answer as stopped", async () => {
    await saveAgentConfig({ ...DEFAULT_AGENT_CONFIG, apiKey: "test-ui-key" });
    vi.spyOn(runner, "runAgent").mockImplementation(async (_c, _m, _d, _p, signal) => new Promise((_resolve, reject) => signal.addEventListener("abort", () => reject(new Error("aborted")), { once: true })));
    render(<AgentView data={createDemoData()} isPreview />);
    fireEvent.change(await screen.findByRole("textbox", { name: "向 Agent 提问" }), { target: { value: "停止测试" } });
    fireEvent.click(screen.getByRole("button", { name: "发送" }));
    await waitFor(() => expect(runner.runAgent).toHaveBeenCalled());
    fireEvent.click(screen.getByRole("button", { name: "停止生成" }));
    await screen.findByText("生成已停止，可重试。");
    expect((await listConversations("preview"))[0]?.messages[1]?.status).toBe("stopped");
  });
});
