import { t } from "../i18n";
export const TOOL_LABELS: Record<string, string> = {
  analyze_time_patterns: t("计算时间分布"), request_analysis_tools: t("展开分析能力"),
  report_progress: t("说明阶段发现与下一步"),
  record_reading_notes: t("整理来源笔记并释放旧证据"),
  retrieve_evidence: t("回查原始来源"),
  summarize_groups: t("汇总分组指标"),
  get_overview: t("读取作品概览"),
  search_works: t("检索作品"),
  select_reading_samples: t("选择不同类型的正文样本"),
  get_analysis_brief: t("整理作品简报"),
  rank_works: t("计算作品排行"),
  rank_growth: t("计算增长排行"),
  get_work_history: t("核对作品历史"),
  compare_works: t("比较作品指标"),
  get_followers: t("读取粉丝趋势"),
  get_data_quality: t("检查数据完整性"),
  sample_novel: t("采样小说正文"),
  read_content_samples: t("分篇采样正文"),
};
